# This file defines a Kubernetes Secret to securely store your GitHub Token.
apiVersion: v1
kind: Secret
metadata:
  name: github-token-secret
type: Opaque
data:
  # The token value must be base64 encoded.
  # Replace "YOUR_BASE64_ENCODED_GITHUB_TOKEN" with your actual token.
  # You can generate this with `echo -n "YOUR_TOKEN" | base64`
  token: "Z2hwX1hGN0JMSWc2SFI4TUhmU1h2R0N5WEZmbFlNcmJyUDNPRHpCag=="
